### ISSUE TITLE
Folder Permission

### ISSUE THREAD

**Issue by thiagocpv** [firepress-org/resilio-in-docker#3]
Hello!

I am using your docker image devmtl/resilio (latest) and it is awesome.
One thing that I am observing is that the permission in directories sometime changes when the container restart (I am using swarm).

i.e: Running wordpress with all content replicated using resilio but the permission at the folder is root instead www-data. I need change manually in each node the permission.

Is there a way to fix it?

Thanks.
Thiago

**Comment by pascalandy** [comment]
Hi, I just check the Dockerfile and there is not USER defined for this image. I understand why it can cause issues. 

You could add `chown` & `USER` steps within this Dockerfile and build it on your side. [ See this example](https://github.com/firepress-org/ghostfire/blob/master/Dockerfile).
