### ISSUE TITLE
ARM architecture

### ISSUE THREAD

**Issue by thiagocpv** [firepress-org/resilio-in-docker#4]
Hi there!

Is possible to build an arm64 architecture, please?

Thanks.
Thiago

**Comment by pascalandy** [comment]
No as I don't maintain this repo anymore. Here is a cue about how to proceed - https://github.com/firepress-org/ghostfire/blob/master/.github/workflows/ci.yml#L255

**Comment by thiagocpv** [comment]
Ok, I have no knowledge enough, but OK.
Thanks.
